import { createContext, useContext, useState, useEffect } from "react";

const translations = {
  en: {
    dir: "ltr",
    // Login page
    welcomeBack: "Welcome back",
    loginSubtext: "Manage bookings across hotels, restaurants, and activities.",
    signInToContinue: "Sign in to continue",
    unifiedPlatform: "Unified Booking Platform",
    controlBooking: "Control every booking",
    inOnePlace: " in one place",
    fiveDesc:
      "Five dashboards for super admin, admin company, hotels, restaurants, and activities. Role-based access, permissions-aware sidebar, and real-time data.",
    security: "Security",
    dashboards: "Dashboards",
    tailoredViews: "5 tailored views",
    emailPlaceholder: "Email",
    passwordPlaceholder: "Password",
    loginBtn: "Login",
    signingIn: "Signing in...",
    sampleAccounts: "Sample accounts",
    loginFailed: "Login Failed",
    invalidCredentials:
      "Invalid credentials. Please check your email and password.",
    tryAgain: "Try Again",
    // Nav / General
    dashboard: "Dashboard",
    settings: "Settings",
    logout: "Logout",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    search: "Search",
    close: "Close",
    loading: "Loading...",
    error: "Error",
    noData: "No data found",
    featured: "FEATURED",
    actions: "Actions",
    exportCsv: "Export CSV",
    amount: "Amount",
    netProfit: "Net Profit",
    financeOverview: "Finance Overview",
    financeSubtitle:
      "Live booking-based financial activity with no placeholder data.",
    loadingFinanceData: "Loading finance data...",
    errorLoadingFinance: "Error loading finance data",
    financeNoRecords: "No finance records available yet.",
    // Hotels
    hotelsManagement: "Hotels Management",
    addHotel: "+ Add Hotel",
    editHotel: "Edit Hotel",
    createHotel: "Create Hotel",
    updateHotel: "Update Hotel",
    deleteHotelConfirm: "Are you sure you want to delete this hotel?",
    errorLoadingHotels: "Error loading hotels. Please check your connection.",
    perNight: "/ night",
    // Restaurants
    restaurantsManagement: "Restaurants Management",
    addRestaurant: "+ Add Restaurant",
    editRestaurant: "Edit Restaurant",
    createRestaurant: "Create Restaurant",
    updateRestaurant: "Update Restaurant",
    deleteRestaurantConfirm: "Are you sure you want to delete this restaurant?",
    errorLoadingRestaurants: "Error loading restaurants.",
    avgPrice: "Avg price",
    // Activities
    activitiesManagement: "Activities Management",
    addActivity: "+ Add Activity",
    editActivity: "Edit Activity",
    createActivity: "Create Activity",
    updateActivity: "Update Activity",
    deleteActivityConfirm: "Are you sure you want to delete this activity?",
    errorLoadingActivities: "Error loading activities.",
    duration: "Duration",
    price: "Price",
    // Settings
    settingsTitle: "Settings",
    settingsSubtitle: "Manage your account and preferences.",
    theme: "Theme",
    lightMode: "Light Mode",
    darkMode: "Dark Mode",
    emailNotificationsLabel: "Email Notifications",
    comingSoonLabel: "Coming soon",
    switchToArabic: "Switch to العربية",
    switchToEnglish: "Switch to English",
    switchToLightMode: "Switch to Light Mode",
    switchToDarkMode: "Switch to Dark Mode",
    profile: "Profile",
    name: "Name",
    email: "Email",
    role: "Role",
    preferences: "Preferences",
    language: "Language",
    emailNotifications: "Email Notifications",
    comingSoon: "Coming soon",
    permissions: "Permissions",
    noPermissions: "No explicit permissions (inherited from role)",
    settingsProfileReadonly:
      "Your profile information is read-only and managed by your administrator.",
    settingsNotificationHint:
      "You'll be able to customize notification preferences here.",
    settingsPermissionHint:
      "Permissions assigned to your account. Managed by your administrator.",
    settingsNoPermissionsHint: "Contact your administrator to grant access.",
    permissionsCountLabel: "permissions granted",
    notifications: "Notifications",
    noNotifications: "No notifications yet",
    viewAll: "View all",
    notif_permissionsUpdated: "Permissions updated",
    notif_permissionsUpdatedBody:
      "Your permissions were updated. Refreshing your access now.",
    notif_iconRequestedTitle: "New Icon Request",
    notif_iconRequestedBody: '{{hotelName}} requested a new icon: "{{label}}"',
    notif_iconDesignedTitle: "Icon Ready",
    notif_iconDesignedBody:
      'Your requested icon "{{label}}" has been designed and is now available.',
    // Users page
    loadingUsers: "Loading users...",
    errorLoadingUsers: "Error loading users",
    usersTeamPlatform: "Platform Team",
    usersTeamCompany: "Company Team",
    usersTeamHotel: "Hotel Team",
    usersTeamRestaurant: "Restaurant Team",
    usersTeamActivity: "Activity Team",
    usersSubPlatform: "Super Admin staff with permission-based access",
    usersSubCompany: "Admin employees of your management company",
    usersSubHotel: "Hotel staff members",
    usersSubRestaurant: "Restaurant staff members",
    usersSubActivity: "Activity staff members",
    usersSubColleaguesPlatform: "Your platform colleagues",
    usersSubColleaguesCompany: "Your company colleagues",
    usersSubColleaguesHotel: "Your hotel colleagues",
    usersSubColleaguesRestaurant: "Your restaurant colleagues",
    usersSubColleaguesActivity: "Your activity colleagues",
    addPlatformMember: "Add Platform Member",
    addTeamMember: "Add Team Member",
    addStaffMember: "Add Staff Member",
    usersPage_addUser: "Add User",
    usersPage_title: "Users",
    superAdminsLabel: "Super Admins",
    staffLabel: "Staff",
    hotelStaffLabel: "Hotel Staff",
    restaurantStaffLabel: "Restaurant Staff",
    activityStaffLabel: "Activity Staff",
    colleaguesLabel: "Colleagues",
    totalPlatformUsers: "Total Platform Users",
    tableView: "Table View",
    editUserBtn: "Edit User",
    deleteUserBtn: "Delete User",
    loadingBookings: "Loading bookings...",
    loadingRooms: "Loading rooms...",
    logo: "Logo",
    createdAt: "Created",
    // Restaurants / Activities page
    restaurantAccounts: "Restaurant Accounts",
    restaurantAccountsSubtitle:
      "Manage restaurant manager accounts linked to admins",
    activityAccounts: "Activity Accounts",
    activityAccountsSubtitle:
      "Manage activity manager accounts linked to admins",
    addRestaurantAccount: "Add Restaurant Account",
    addActivityAccount: "Add Activity Account",
    noRestaurantAccounts: "No restaurant accounts yet. Add one to get started.",
    noActivityAccounts: "No activity accounts yet. Add one to get started.",
    restaurantAccountsTable: "Restaurant Accounts Table",
    activityAccountsTable: "Activity Accounts Table",
    confirmDeleteRestaurant:
      "Are you sure you want to delete this restaurant account?",
    confirmDeleteActivity:
      "Are you sure you want to delete this activity account?",
    confirmDeleteUser: "Are you sure you want to delete this user?",
    dashboardReadOnlyNotice:
      "Control panel is read-only. Use dedicated sidebar pages to add, edit, or delete data.",
    // Sidebar items
    users: "Users",
    admins: "Admins",
    allHotels: "All Hotels",
    allRestaurants: "All Restaurants",
    allActivities: "All Activities",
    allBookings: "All Bookings",
    roomsTables: "Rooms/Tables",
    finance: "Finance",
    reports: "Reports",
    hotelMainDetails: "Hotel Main Details",
    iconsLibrary: "Icons Library",
    channelManager: "Channel Manager",
    travky: "Travky",
    external: "External",
    guestGroups: "Guest Groups",
    guestGroupDetails: "Guest Group Details",
    guestGroupStepMain: "Main Details",
    guestGroupStepNationalities: "Nationalities",
    guestGroupStepPreview: "Preview",
    mealPlans: "Meal Plans",
    periods: "Periods",
    supplements: "Supplement",
    refundPolicies: "Refund Policy",
    channelManagerRooms: "Rooms",
    commission: "Commission",
    rates: "Rates",
    availability: "Availability",
    stopSale: "Stop Sale",
    apiSettings: "API Settings",
    // Sidebar – new super-admin sections
    platformFees: "Platform Fees",
    platformFeesHotels: "Hotel Fees",
    customerServices: "Customer Services",
    manualBooking: "Manual Booking",
    // Platform Fees – Hotels page
    pfPage_title: "Platform Fees – Hotels",
    pfPage_subtitle: "Manage platform fees and minimum commission thresholds",
    pfScope_label: "Application Scope",
    pfScope_allHotels: "All Hotels",
    pfScope_byCountry: "By Country",
    pfScope_byCity: "By City",
    pfScope_specificHotel: "Specific Hotel",
    pfField_platformFee: "% Platform Fee",
    pfField_minCommission: "Minimum Commission",
    pfField_minCommissionHint: "Minimum the hotel can set as its commission",
    pfSaved: "Saved!",
    // Manual Booking page
    mb_pageTitle: "Manual Booking",
    mb_pageSubtitle: "Create a booking on behalf of a customer",
    mb_heroSlogan: "احجز تجربتك القادمة",
    mb_tabHotels: "فنادق",
    mb_tabActivities: "أنشطة",
    mb_tabPackages: "باقات",
    mb_country: "Country / Region",
    mb_allCountries: "All Countries",
    mb_countryEgypt: "Egypt",
    mb_countryUAE: "UAE",
    mb_countrySaudi: "Saudi Arabia",
    mb_checkIn: "Check-in",
    mb_checkOut: "Check-out",
    mb_roomsGuests: "Rooms & Guests",
    mb_room: "room",
    mb_rooms: "Rooms",
    mb_adults: "Adults",
    mb_children: "Children",
    mb_searchBtn: "Search",
    mb_popularDestinations: "Popular Destinations",
    mb_popularSubtitle: "Lowest prices from Travky users",
    mb_startingFrom: "Starting from",
    mb_bookNow: "Book Now",
    hotelPreview: "Preview Hotel",
    hotelStepMain: "Main Details",
    hotelStepDescription: "Description",
    hotelStepIcons: "Icons",
    hotelStepPolicy: "Policy",
    hotelStepPhotos: "Photos",
    activityMainDetails: "Activity Details",
    activityStepMain: "Basic Details",
    activityStepDescription: "Description",
    activityStepIcons: "Amenities",
    activityStepPolicy: "Policies",
    activityStepPhotos: "Photos",
    unifiedBookingPlatform: "Unified Booking Platform",
    // Form fields
    basicInfo: "Basic Information",
    location: "Location",
    contact: "Contact",
    details: "Details",
    amenities: "Amenities",
    policies: "Policies",
    pricing: "Pricing",
    status: "Status",
    active: "Active",
    inactive: "Inactive",
    description: "Description",
    address: "Address",
    city: "City",
    country: "Country",
    phone: "Phone",
    website: "Website",
    type: "Type",
    stars: "Stars",
    saving: "Saving...",
    // User Form Modal
    createNewUser: "Create New User",
    editUser: "Edit User",
    createUser: "Create User",
    updateUser: "Update User",
    basicInfoTab: "Basic Info",
    permissionsTab: "Permissions",
    fullName: "Full Name",
    emailAddress: "Email Address",
    leaveEmptyPassword: "(leave empty to keep current)",
    linkedAdmin: "Linked Admin (Company)",
    adminRequired: "Admin is required for this account type",
    selectAdmin: "-- Select Admin --",
    logoUpload: "Logo Image",
    logoPreview: "Logo preview",
    roleDescription: "Role Description",
    useCustomPerms: "Use custom permissions (override role defaults)",
    selectAll: "Select All",
    clearAll: "Clear All",
    applyRolePreset: "Apply Role Preset",
    permissionsSelected: "permissions selected",
    permSummary: "Permission Summary",
    noPermsSelected: "No permissions selected",
    // Role names & descriptions
    role_super_admin: "Super Admin",
    role_admin: "Admin (Company)",
    role_hotel: "Hotel Account",
    role_restaurant: "Restaurant Account",
    role_activity: "Activity Account",
    role_hotel_manager: "Hotel Manager",
    role_restaurant_manager: "Restaurant Manager",
    role_activity_manager: "Activity Manager",
    roleDesc_super_admin:
      "Full access to all system features. Can manage all users, hotels, restaurants, activities, and system settings.",
    roleDesc_admin:
      "Company administrator. Can manage hotels, restaurants, and activities under their company.",
    roleDesc_hotel:
      "Hotel manager. Can manage rooms, bookings, and view reports for their hotel.",
    roleDesc_restaurant:
      "Restaurant manager. Can manage tables, reservations, and view reports for their restaurant.",
    roleDesc_activity:
      "Activity manager. Can manage activities and bookings for their activities.",
    // Permission modules
    module_users: "Users Management",
    module_admins: "Admins Management",
    module_hotels: "Hotels",
    module_hotel: "Hotel Details",
    module_channel_manager: "Channel Manager",
    module_channel_manager_travky: "Travky",
    module_channel_manager_external: "External",
    module_guest_groups: "Guest Groups",
    module_meal_plans: "Meal Plans",
    module_periods: "Periods",
    module_supplements: "Supplements",
    module_refund_policies: "Refund Policies",
    module_channel_manager_rooms: "Channel Manager Rooms",
    module_rates: "Rates",
    module_availability: "Availability",
    module_restaurants: "Restaurants",
    module_activities: "Activities",
    module_bookings: "Bookings",
    module_rooms: "Rooms / Tables",
    module_finance: "Finance",
    module_reports: "Reports",
    module_settings: "Settings",
    // Permission actions
    action_view_users: "View Users",
    action_add_users: "Add Users",
    action_edit_users: "Edit Users",
    action_delete_users: "Delete Users",
    action_view_admins: "View Admins",
    action_add_admins: "Add Admins",
    action_edit_admins: "Edit Admins",
    action_delete_admins: "Delete Admins",
    action_view_hotels: "View Hotels",
    action_add_hotels: "Add Hotels",
    action_edit_hotels: "Edit Hotels",
    action_delete_hotels: "Delete Hotels",
    action_view_restaurants: "View Restaurants",
    action_add_restaurants: "Add Restaurants",
    action_edit_restaurants: "Edit Restaurants",
    action_delete_restaurants: "Delete Restaurants",
    action_view_activities: "View Activities",
    action_add_activities: "Add Activities",
    action_edit_activities: "Edit Activities",
    action_delete_activities: "Delete Activities",
    action_view_bookings: "View Bookings",
    action_add_bookings: "Add Bookings",
    action_edit_bookings: "Edit Bookings",
    action_delete_bookings: "Delete Bookings",
    action_view_rooms: "View Rooms",
    action_add_rooms: "Add Rooms",
    action_edit_rooms: "Edit Rooms",
    action_delete_rooms: "Delete Rooms",
    action_view_finance: "View Finance",
    action_add_finance: "Add Transactions",
    action_edit_finance: "Edit Transactions",
    action_delete_finance: "Delete Transactions",
    action_view_reports: "View Reports",
    action_view_settings: "View Settings",
    action_edit_settings: "Edit Settings",
    action_details_hotel: "Manage Hotel Main Details",
    action_view_channel_manager: "View Channel Manager",
    action_view_channel_manager_travky: "View Travky",
    action_view_channel_manager_external: "View External Channels",
    action_view_guest_groups: "View Guest Groups",
    action_view_meal_plans: "View Meal Plans",
    action_view_periods: "View Periods",
    action_view_supplements: "View Supplements",
    action_view_refund_policies: "View Refund Policies",
    action_view_channel_manager_rooms: "View Channel Rooms",
    action_view_rates: "View Rates",
    action_view_availability: "View Availability",
    dangerLabel: "DANGER",
    allLabel: "All",
    // Admins page
    adminsManagement: "Admins Management",
    adminsSubtitle:
      "Company administrators — manage hotels, restaurants & activities",
    addAdmin: "+ Add Admin",
    totalAdmins: "Total Admins",
    withPermissions: "With Permissions",
    managedAccounts: "Managed Accounts",
    editAdmin: "Edit Admin",
    areYouSureDeleteAdmin: "Are you sure you want to delete this admin?",
    loadingAdmins: "Loading admins...",
    errorLoadingAdmins: "Error loading admins",
    permissionsLabel: "Permissions",
    moreLabel: "more",
    // Hotels page
    hotelAccounts: "Hotel Accounts",
    hotelAccountsSubtitle:
      "Manage hotel user accounts — each must be linked to an Admin",
    addHotelAccount: "+ Add Hotel Account",
    linkedToAdmin: "Linked to Admin",
    noAdminLinked: "No Admin Linked",
    noAdminWarning: "NO ADMIN",
    loadingHotelAccounts: "Loading hotel accounts...",
    errorLoadingData: "Error loading data",
    hotelAccountsTable: "All Hotel Accounts (Table View)",
    areYouSureDeleteHotelAccount:
      "Are you sure you want to delete this hotel account?",
    noHotelAccountsYet:
      'No hotel accounts yet. Click "+ Add Hotel Account" to create one.',
    adminRequiredForHotelTitle: "Admin account required",
    adminRequiredForHotelMessage:
      "You can't add a hotel account until at least one admin account exists. Create an admin first, then continue with hotel creation.",
    createAdminNow: "Add Admin Now",
    // SuperAdmin dashboard
    superAdminOverview: "Super Admin Overview",
    managePlatformResources: "Manage all platform resources from here.",
    superAdminUsers: "Super Admin Users",
    bookings: "Bookings",
    additionalServices: "Additional Services",
    adminDashboardTitle: "Admin Company Dashboard",
    adminDashboardSubtitle:
      "View hotels, restaurants, activities, and operations in one read-only control panel.",
    // Table column labels
    guest: "Guest",
    checkIn: "Check-in",
    checkOut: "Check-out",
    capacity: "Capacity",
    roomTableNum: "Room/Table #",
    date: "Date",
    revenue: "Revenue",
    expenses: "Expenses",
    reportTitle: "Report",
    generatedAt: "Generated",
    // Reports page
    reportsSubtitle: "Booking-based reports grouped by type and month.",
    reportName: "Report",
    reportType: "Type",
    reportPeriod: "Period",
    reportPeriodAllTime: "All Time",
    reportGenerated: "Generated",
    reportStatus: "Status",
    reportReady: "Ready",
    reportProcessing: "Processing",
    reportTotal: "Total Reports",
    reportThisMonth: "This Month",
    reportNoRecords:
      "No reports available yet. Bookings will generate reports automatically.",
    reportTypeMonthly: "Monthly",
    reportTypeBookings: "Bookings",
    reportTypeStatus: "Status",
    loadingReportsData: "Loading reports...",
    errorLoadingReports: "Error loading reports",
    // Permission action labels
    view: "View",
    manage: "Manage",
    // Rooms page
    roomsPage_totalRooms: "Total Rooms",
    roomsPage_available: "Available",
    roomsPage_occupied: "Occupied",
    roomsPage_maintenance: "Maintenance",
    roomsPage_reserved: "Reserved",
    roomsPage_searchPlaceholder: "Search rooms...",
    roomsPage_allStatuses: "All Statuses",
    roomsPage_addRoom: "+ Add Room",
    roomsPage_noRooms: "No rooms found",
    roomsPage_guests: "guests",
    roomsPage_deleteRoomTitle: "Delete Room #",
    roomsPage_deleteCannotUndo: "This action cannot be undone.",
    // Bookings page
    bkPage_totalBookings: "Total Bookings",
    bkPage_confirmed: "Confirmed",
    bkPage_checkedIn: "Checked In",
    bkPage_pendingPayment: "Pending Payment",
    bkPage_searchPlaceholder: "Search by name, ref, room...",
    bkPage_allStatuses: "All Statuses",
    bkPage_allPayments: "All Payments",
    bkPage_newBooking: "+ New Booking",
    bkPage_noBookings: "No bookings found",
    bkPage_colRef: "Reference",
    bkPage_colGuest: "Guest",
    bkPage_colRoom: "Room",
    bkPage_colCheckIn: "Check-in",
    bkPage_colCheckOut: "Check-out",
    bkPage_colTotal: "Total",
    bkPage_colStatus: "Status",
    bkPage_colPayment: "Payment",
    bkPage_deleteBookingTitle: "Delete Booking?",
    // Room form modal
    rm_addTitle: "Add New Room",
    rm_editTitle: "Edit Room",
    rm_subtitle: "Fill in the room details below",
    rm_tabBasic: "Basic",
    rm_tabPricing: "Pricing",
    rm_tabAmenities: "Amenities",
    rm_tabPhotos: "Photos",
    rm_secIdentity: "Room Identity",
    rm_secCapacity: "Capacity & Beds",
    rm_secFeatures: "Room Features",
    rm_secPricingDetails: "Pricing Details",
    rm_secAmenities: "Room Amenities",
    rm_secPhotos: "Room Photos",
    rm_fieldNumber: "Room / Table # *",
    rm_fieldName: "Room Name",
    rm_fieldType: "Type",
    rm_fieldCategory: "Category",
    rm_fieldFloor: "Floor",
    rm_fieldStatus: "Status",
    rm_fieldGuests: "Guests",
    rm_fieldBeds: "Beds",
    rm_fieldBedType: "Bed Type",
    rm_fieldBathrooms: "Bathrooms",
    rm_fieldSize: "Size (m²)",
    rm_fieldView: "View",
    rm_fieldSmoking: "Smoking Allowed",
    rm_fieldPets: "Pets Allowed",
    rm_fieldDesc: "Description",
    rm_descPlaceholder: "Describe the room experience...",
    rm_fieldPrice: "Price per Night *",
    rm_fieldCurrency: "Currency",
    rm_fieldDiscount: "Discount (%)",
    rm_pricingSummary: "Pricing Summary",
    rm_basePrice: "Base price / night",
    rm_finalPrice: "Final price / night",
    rm_perWeek: "Per week (7 nights)",
    rm_perMonth: "Per month (30 nights)",
    rm_typeRoom: "Room",
    rm_typeSuite: "Suite",
    rm_typeStudio: "Studio",
    rm_typeVilla: "Villa",
    rm_typeTable: "Table (Restaurant)",
    rm_typeService: "Service / Other",
    rm_catStandard: "Standard",
    rm_catDeluxe: "Deluxe",
    rm_catSuperior: "Superior",
    rm_catExecutive: "Executive",
    rm_catPresidential: "Presidential",
    rm_statusAvailable: "Available",
    rm_statusOccupied: "Occupied",
    rm_statusReserved: "Reserved",
    rm_statusMaintenance: "Maintenance",
    rm_bedSingle: "Single",
    rm_bedDouble: "Double",
    rm_bedQueen: "Queen",
    rm_bedKing: "King",
    rm_bedTwin: "Twin",
    rm_bedSofa: "Sofa Bed",
    rm_viewNone: "No specific view",
    rm_viewSea: "Sea View",
    rm_viewPool: "Pool View",
    rm_viewCity: "City View",
    rm_viewGarden: "Garden View",
    rm_viewMountain: "Mountain View",
    rm_amenityIncluded: "Included",
    rm_amenityNotIncluded: "Not included",
    rm_amenityToggleHint: "Click to toggle amenities",
    rm_photosUploadHint: "Click or drag & drop photos",
    rm_photosLimit: "Up to 8 images — JPEG / PNG / WebP",
    rm_photoMain: "MAIN",
    rm_photoSetMain: "Main",
    rm_errNumber: "Room / Table number is required.",
    rm_errPrice: "Price per night is required.",
    rm_errSave: "Failed to save room.",
    rm_addBtn: "Add Room",
    rm_updateBtn: "Update Room",
    // Booking form modal
    bk_addTitle: "New Booking",
    bk_editTitle: "Edit Booking",
    bk_tabGuest: "Guest",
    bk_tabStay: "Stay",
    bk_tabPayment: "Payment",
    bk_tabNotes: "Notes",
    bk_secGuestInfo: "Guest Information",
    bk_secGuestCount: "Guest Count",
    bk_secStay: "Stay Details",
    bk_secRoom: "Room Assignment",
    bk_secPayment: "Payment Details",
    bk_secNotes: "Requests & Notes",
    bk_fieldName: "Full Name *",
    bk_fieldEmail: "Email Address",
    bk_fieldPhone: "Phone Number",
    bk_fieldNationality: "Nationality",
    bk_fieldSource: "Booking Source",
    bk_fieldAdults: "Adults",
    bk_fieldChildren: "Children",
    bk_srcDirect: "Direct",
    bk_srcOnline: "Online",
    bk_srcPhone: "Phone",
    bk_srcWalkIn: "Walk-in",
    bk_srcAgency: "Agency",
    bk_fieldBookingType: "Booking Type",
    bk_fieldBookingStatus: "Booking Status",
    bk_fieldCheckIn: "Check-in Date *",
    bk_fieldCheckOut: "Check-out Date *",
    bk_typeHotel: "Hotel",
    bk_typeRestaurant: "Restaurant",
    bk_typeActivity: "Activity",
    bk_statusPending: "Pending",
    bk_statusConfirmed: "Confirmed",
    bk_statusCheckedIn: "Checked In",
    bk_statusCheckedOut: "Checked Out",
    bk_statusCancelled: "Cancelled",
    bk_statusNoShow: "No Show",
    bk_night: "night",
    bk_nights: "nights",
    bk_duration: "Duration",
    bk_fieldSelectRoom: "Select Room",
    bk_noRoomAssigned: "No room assigned",
    bk_fieldPricePerNight: "Price per Night",
    bk_fieldPaymentMethod: "Payment Method",
    bk_fieldPaymentStatus: "Payment Status",
    bk_fieldDiscount: "Discount (%)",
    bk_fieldTaxRate: "Tax Rate (%)",
    bk_fieldPaid: "Amount Paid",
    bk_pmCash: "Cash",
    bk_pmCard: "Credit / Debit Card",
    bk_pmBank: "Bank Transfer",
    bk_pmOnline: "Online",
    bk_pmOther: "Other",
    bk_psUnpaid: "Unpaid",
    bk_psPartial: "Partial",
    bk_psPaid: "Fully Paid",
    bk_psRefunded: "Refunded",
    bk_summaryTitle: "Booking Summary",
    bk_summaryNightsRate: "Nights × Rate",
    bk_summarySubtotal: "Subtotal",
    bk_summaryDiscount: "Discount",
    bk_summaryTax: "Tax",
    bk_summaryTotal: "Total",
    bk_summaryPaid: "Paid",
    bk_summaryBalance: "Balance Due",
    bk_fieldSpecialReq: "Special Requests (from guest)",
    bk_fieldGuestNotes: "Guest Notes",
    bk_fieldInternalNotes: "Internal Notes (staff only)",
    bk_fieldSpecialReqPlaceholder:
      "e.g. High floor, extra pillows, anniversary decoration...",
    bk_fieldGuestNotesPlaceholder: "Any additional notes from the guest...",
    bk_fieldInternalNotesPlaceholder:
      "Internal staff notes (not shown to guests)...",
    bk_errName: "Customer name is required.",
    bk_errCheckIn: "Check-in date is required.",
    bk_errCheckOut: "Check-out date is required.",
    bk_errDates: "Check-out must be after check-in.",
    bk_errSave: "Failed to save booking.",
    bk_confirmBtn: "Confirm Booking",
    bk_updateBtn: "Update Booking",
    bk_footerTotal: "Total",
    // Dashboard shared keys
    dashboardWelcomeLine: "Welcome back,",
    dashboardPlatformOverview: "Here's an overview of your platform.",
    dashboardBusinessOverview:
      "Here's what's happening with your business today.",
    // Dashboard stat card titles
    dashboardCardPlatformRevenue: "Platform Revenue",
    dashboardCardAdminAccounts: "Admin Accounts",
    dashboardCardTotalBookings: "Total Bookings",
    dashboardCardManagedEntities: "Managed Entities",
    dashboardCardTotalRevenue: "Total Revenue",
    dashboardCardManagedAccounts: "Managed Accounts",
    dashboardCardTeamMembers: "Team Members",
    dashboardCardAvailableRooms: "Available Rooms",
    dashboardCardActivities: "Activities Listed",
    dashboardCardAvailableTables: "Available Tables",
    dashboardCardTotalReservations: "Total Reservations",
    // Dashboard donut chart segments
    dashboardSegmentHotels: "Hotels",
    dashboardSegmentRestaurants: "Restaurants",
    dashboardSegmentActivities: "Activities",
    dashboardSegmentAdmins: "Admins",
    dashboardSegmentConfirmed: "Confirmed",
    dashboardSegmentPending: "Pending",
    dashboardSegmentCheckedIn: "Checked In",
    dashboardSegmentCancelled: "Cancelled",
    dashboardSegmentSeated: "Seated",
    // Dashboard donut chart titles
    dashboardEntityDistribution: "Entity Distribution",
    dashboardEntityDistributionSubtitle: "Breakdown by managed account type",
    dashboardAccountTypes: "Account Distribution",
    dashboardAccountTypesSubtitle: "Breakdown by account type",
    dashboardBookingStatus: "Booking Status",
    dashboardBookingStatusSubtitle: "Distribution by booking status",
    dashboardReservationStatus: "Reservation Status",
    dashboardReservationStatusSubtitle: "Distribution by reservation status",
    dashboardTotalLabel: "Total",
    dashboardVisitsLabel: "Total",
    // Dashboard overview chart
    dashboardTabRevenue: "Revenue",
    dashboardTabOrders: "Orders",
    dashboardTabProfit: "Profit",
    dashboardTabBookings: "Bookings",
    dashboardTabReservations: "Reservations",
    dashboardOverviewTitle: "Revenue Overview",
    dashboardOverviewSubtitle:
      "Monthly performance — revenue, bookings & profit",
    // Dashboard monthly goals
    dashboardMonthlyGoalsTitle: "Monthly Goals",
    dashboardMonthlyGoalsSubtitle: "Progress toward this month's targets",
    dashboardNoGoals: "No goals configured",
    // Dashboard goal labels
    dashboardGoalPlatformRevenue: "Platform Revenue",
    dashboardGoalBookings: "Total Bookings",
    dashboardGoalManagedEntities: "Managed Entities",
    dashboardGoalRevenue: "Revenue Target",
    dashboardGoalManagedAccounts: "Managed Accounts",
    dashboardGoalOccupancyRate: "Occupancy Rate",
    dashboardGoalReservations: "Reservations Target",
    dashboardGoalTableUtilization: "Table Utilization",
    dashboardGoalActivitiesListed: "Activities Listed",
    // DataModal labels
    dataModal_manage: "Data Management",
    dataModal_title: "Data Management",
    dataModal_export: "Export Data",
    dataModal_exportDesc: "Download all records as .xlsx",
    dataModal_import: "Import Data",
    dataModal_importDesc: "Upload an .xlsx file to bulk-add records",
    dataModal_template: "Download Template",
    dataModal_templateDesc: "Get a blank Excel template to fill in",
    dataModal_exporting: "Exporting…",
    dataModal_exportSuccess: "Data exported successfully!",
    dataModal_exportError: "Export failed. Please try again.",
    dataModal_downloading: "Downloading template…",
    dataModal_templateSuccess: "Template downloaded!",
    dataModal_templateError: "Download failed. Please try again.",
    dataModal_importing: "Importing…",
    dataModal_importSuccess: "Import complete!",
    dataModal_rowsImported: "rows imported",
    dataModal_importError: "Import failed.",
    // Refund Policies page
    rp_title: "Refund Policies",
    rp_subtitle: "Set cancellation and refund rules",
    rp_policyType: "Policy Type",
    rp_daysBeforeArrival: "Days Before Arrival",
    rp_fees: "Fees",
    rp_extraPrice: "Extra Price",
    rp_extraPriceHint: "Extra price added on top of the room price for this plan",
    rp_noData: "No refund policies yet",
    rp_days: "days",
    rp_day: "day",
    rp_30day: "30 days",
    rp_1day: "1 day",
    rp_typeNonRefundable: "Non-Refundable",
    rp_typeFreeCancellation: "Free Cancellation",
    rp_typePartial: "Partial",
    rp_viewTitle: "View Refund Policy",
    rp_editTitle: "Edit Policy",
    rp_addTitle: "Add Refund Policy",
    rp_fieldName: "Name",
    rp_fieldFeesPercent: "Fees (%)",
    rp_feeCalcMethod: "Fee Calculation Method",
    rp_fixedAmount: "Fixed Amount",
    rp_percentage: "% Percentage",
    rp_fixedPerGroup: "Fixed per Group",
    rp_nameRequired: "Name is required",
    // Periods page
    per_title: "Periods",
    per_subtitle: "Set seasonal periods and prices",
    per_fieldName: "Name",
    per_fieldFrom: "From",
    per_fieldTo: "To",
    per_noData: "No periods added yet",
    per_viewTitle: "View Period",
    per_editTitle: "Edit Period",
    per_addTitle: "Add Period",
    per_nameRequired: "Name is required",
    per_fromRequired: "Start date is required",
    per_toRequired: "End date is required",
    per_toAfterFrom: "End date must be after start date",
    // Commission page
    comm_subtitle: "{{count}} commissions added",
    comm_addBtn: "Add Commission",
    comm_viewTitle: "Commission Details",
    comm_editTitle: "Edit Commission",
    comm_addTitle: "Add Commission",
    comm_fieldName: "Commission Name",
    comm_fieldType: "Commission Type",
    comm_fieldValue: "Value",
    comm_fieldValuePercent: "Value (%)",
    comm_fieldValueFixed: "Value (Fixed Amount)",
    comm_fieldAppliesTo: "Applies To",
    comm_fieldNotes: "Notes",
    comm_namePlaceholder: "e.g. Travel Agent Commission",
    comm_notesPlaceholder: "Additional notes...",
    comm_nameRequired: "Commission name is required",
    comm_valueRequired: "Commission value must be a positive number",
    comm_active: "Active",
    comm_inactive: "Inactive",
    comm_deactivate: "Deactivate",
    comm_activate: "Activate",
    comm_fixed: "fixed",
    comm_noData: "No commissions added",
    comm_saveChanges: "Save Changes",
    comm_pageTitle: "Commission",
    comm_pageSubtitle: "Set the minimum platform commission from bookings",
    comm_b2cTitle: "B2C",
    comm_b2cSubtitle: "Direct bookings commission",
    comm_b2bTitle: "B2B",
    comm_b2bSubtitle: "B2B bookings commission",
    comm_platformFees: "Platform Fees",
    comm_minLabel: "Minimum Commission",
    comm_totalLabel: "Total",
    comm_formulaNote: "Formula: Platform Fees + Minimum Commission = Total. Platform fees are fixed and cannot be changed.",
    comm_next: "Next",
    comm_saved: "Saved!",
  },
  ar: {
    dir: "rtl",
    // Login page
    welcomeBack: "مرحباً بك",
    loginSubtext: "إدارة الحجوزات عبر الفنادق والمطاعم والأنشطة.",
    signInToContinue: "سجّل دخولك للمتابعة",
    unifiedPlatform: "منصة الحجز الموحّدة",
    controlBooking: "تحكّم في كل حجز",
    inOnePlace: " في مكان واحد",
    fiveDesc:
      "خمس لوحات تحكم للمسؤول الرئيسي وشركة الإدارة والفنادق والمطاعم والأنشطة. وصول قائم على الأدوار وشريط جانبي وبيانات فورية.",
    security: "الأمان",
    dashboards: "لوحات التحكم",
    tailoredViews: "5 طرق عرض مخصصة",
    emailPlaceholder: "البريد الإلكتروني",
    passwordPlaceholder: "كلمة المرور",
    loginBtn: "تسجيل الدخول",
    signingIn: "جاري تسجيل الدخول...",
    sampleAccounts: "حسابات تجريبية",
    loginFailed: "فشل تسجيل الدخول",
    invalidCredentials:
      "بيانات غير صحيحة. يرجى التحقق من البريد الإلكتروني وكلمة المرور.",
    tryAgain: "حاول مرة أخرى",
    // Nav / General
    dashboard: "لوحة التحكم",
    settings: "الإعدادات",
    logout: "تسجيل الخروج",
    save: "حفظ",
    cancel: "إلغاء",
    delete: "حذف",
    edit: "تعديل",
    add: "إضافة",
    search: "بحث",
    close: "إغلاق",
    loading: "جاري التحميل...",
    error: "خطأ",
    noData: "لا توجد بيانات",
    featured: "مميز",
    actions: "إجراءات",
    exportCsv: "تصدير CSV",
    amount: "المبلغ",
    netProfit: "صافي الربح",
    financeOverview: "نظرة عامة مالية",
    financeSubtitle:
      "نشاط مالي مباشر مبني على الحجوزات بدون أي بيانات تجريبية.",
    loadingFinanceData: "جاري تحميل البيانات المالية...",
    errorLoadingFinance: "حدث خطأ أثناء تحميل البيانات المالية",
    financeNoRecords: "لا توجد سجلات مالية حالياً.",
    // Hotels
    hotelsManagement: "إدارة الفنادق",
    addHotel: "+ إضافة فندق",
    editHotel: "تعديل الفندق",
    createHotel: "إنشاء فندق",
    updateHotel: "تحديث الفندق",
    deleteHotelConfirm: "هل أنت متأكد من حذف هذا الفندق؟",
    errorLoadingHotels: "خطأ في تحميل الفنادق. يرجى التحقق من الاتصال.",
    perNight: "/ ليلة",
    // Restaurants
    restaurantsManagement: "إدارة المطاعم",
    addRestaurant: "+ إضافة مطعم",
    editRestaurant: "تعديل المطعم",
    createRestaurant: "إنشاء مطعم",
    updateRestaurant: "تحديث المطعم",
    deleteRestaurantConfirm: "هل أنت متأكد من حذف هذا المطعم؟",
    errorLoadingRestaurants: "خطأ في تحميل المطاعم.",
    avgPrice: "متوسط السعر",
    // Activities
    activitiesManagement: "إدارة الأنشطة",
    addActivity: "+ إضافة نشاط",
    editActivity: "تعديل النشاط",
    createActivity: "إنشاء نشاط",
    updateActivity: "تحديث النشاط",
    deleteActivityConfirm: "هل أنت متأكد من حذف هذا النشاط؟",
    errorLoadingActivities: "خطأ في تحميل الأنشطة.",
    duration: "المدة",
    price: "السعر",
    // Settings
    settingsTitle: "الإعدادات",
    settingsSubtitle: "إدارة حسابك وتفضيلاتك.",
    theme: "المظهر",
    lightMode: "وضع نهاري",
    darkMode: "وضع ليلي",
    emailNotificationsLabel: "إشعارات البريد الإلكتروني",
    comingSoonLabel: "قريباً",
    switchToArabic: "التبديل إلى العربية",
    switchToEnglish: "التبديل إلى الإنجليزية",
    switchToLightMode: "التبديل إلى الوضع النهاري",
    switchToDarkMode: "التبديل إلى الوضع الليلي",
    profile: "الملف الشخصي",
    name: "الاسم",
    email: "البريد الإلكتروني",
    role: "الدور",
    preferences: "التفضيلات",
    language: "اللغة",
    emailNotifications: "إشعارات البريد الإلكتروني",
    comingSoon: "قريباً",
    permissions: "الصلاحيات",
    noPermissions: "لا توجد صلاحيات محددة (موروثة من الدور)",
    settingsProfileReadonly: "معلومات ملفك الشخصي للقراءة فقط ويديرها مسؤولك.",
    settingsNotificationHint: "ستتمكن من تخصيص تفضيلات الإشعارات هنا.",
    settingsPermissionHint: "الصلاحيات المرتبطة بحسابك. يديرها مسؤولك.",
    settingsNoPermissionsHint: "تواصل مع مسؤولك لمنح الصلاحيات.",
    permissionsCountLabel: "صلاحية ممنوحة",
    notifications: "الإشعارات",
    noNotifications: "لا توجد إشعارات بعد",
    viewAll: "عرض الكل",
    notif_permissionsUpdated: "تم تحديث الصلاحيات",
    notif_permissionsUpdatedBody:
      "تم تحديث صلاحياتك. يتم الآن تحديث وصولك تلقائياً.",
    notif_iconRequestedTitle: "طلب أيقونة جديد",
    notif_iconRequestedBody: 'طلب {{hotelName}} أيقونة جديدة: "{{label}}"',
    notif_iconDesignedTitle: "الأيقونة جاهزة",
    notif_iconDesignedBody:
      'تم تصميم الأيقونة المطلوبة "{{label}}" وهي متاحة الآن.',
    // Users page
    loadingUsers: "جارٍ تحميل المستخدمين...",
    errorLoadingUsers: "خطأ في تحميل المستخدمين",
    usersTeamPlatform: "فريق المنصة",
    usersTeamCompany: "فريق الشركة",
    usersTeamHotel: "فريق الفندق",
    usersTeamRestaurant: "فريق المطعم",
    usersTeamActivity: "فريق النشاط",
    usersSubPlatform: "موظفو المسؤول الرئيسي بصلاحيات مخصصة",
    usersSubCompany: "موظفو إدارة الشركة",
    usersSubHotel: "موظفو الفندق",
    usersSubRestaurant: "موظفو المطعم",
    usersSubActivity: "موظفو النشاط",
    usersSubColleaguesPlatform: "زملاؤك في المنصة",
    usersSubColleaguesCompany: "زملاؤك في الشركة",
    usersSubColleaguesHotel: "زملاؤك في الفندق",
    usersSubColleaguesRestaurant: "زملاؤك في المطعم",
    usersSubColleaguesActivity: "زملاؤك في النشاط",
    addPlatformMember: "إضافة عضو للمنصة",
    addTeamMember: "إضافة عضو للفريق",
    addStaffMember: "إضافة موظف",
    usersPage_addUser: "إضافة مستخدم",
    usersPage_title: "المستخدمون",
    superAdminsLabel: "مسؤولو النظام",
    staffLabel: "الموظفون",
    hotelStaffLabel: "موظفو الفندق",
    restaurantStaffLabel: "موظفو المطعم",
    activityStaffLabel: "موظفو النشاط",
    colleaguesLabel: "الزملاء",
    totalPlatformUsers: "إجمالي مستخدمي المنصة",
    tableView: "عرض الجدول",
    editUserBtn: "تعديل المستخدم",
    deleteUserBtn: "حذف المستخدم",
    loadingBookings: "جارٍ تحميل الحجوزات...",
    loadingRooms: "جارٍ تحميل الغرف...",
    logo: "الشعار",
    createdAt: "تاريخ الإنشاء",
    // Restaurants / Activities page
    restaurantAccounts: "حسابات المطاعم",
    restaurantAccountsSubtitle: "إدارة حسابات مديري المطاعم المرتبطة بالمدراء",
    activityAccounts: "حسابات الأنشطة",
    activityAccountsSubtitle: "إدارة حسابات مديري الأنشطة المرتبطة بالمدراء",
    addRestaurantAccount: "إضافة حساب مطعم",
    addActivityAccount: "إضافة حساب نشاط",
    noRestaurantAccounts: "لا توجد حسابات مطاعم بعد. أضف واحداً للبدء.",
    noActivityAccounts: "لا توجد حسابات أنشطة بعد. أضف واحداً للبدء.",
    restaurantAccountsTable: "جدول حسابات المطاعم",
    activityAccountsTable: "جدول حسابات الأنشطة",
    confirmDeleteRestaurant: "هل أنت متأكد من حذف هذا الحساب؟",
    confirmDeleteActivity: "هل أنت متأكد من حذف هذا الحساب؟",
    confirmDeleteUser: "هل أنت متأكد من حذف هذا المستخدم؟",
    dashboardReadOnlyNotice:
      "لوحة التحكم للعرض فقط. استخدم الصفحات المخصصة في الشريط الجانبي للإضافة أو التعديل أو الحذف.",
    // Sidebar items
    users: "المستخدمون",
    admins: "المدراء",
    myTeam: "فريقي",
    allHotels: "جميع الفنادق",
    myHotels: "فنادقي",
    allRestaurants: "جميع المطاعم",
    myRestaurants: "مطاعمي",
    allActivities: "جميع الأنشطة",
    myActivities: "أنشطتي",
    allBookings: "جميع الحجوزات",
    roomsTables: "الغرف/الطاولات",
    rooms: "الغرف",
    tables: "الطاولات",
    reservations: "الحجوزات",
    additionalServices: "الخدمات الإضافية",
    activities: "الأنشطة",
    bookings: "الحجوزات",
    finance: "المالية",
    reports: "التقارير",
    hotelMainDetails: "بيانات الفندق",
    iconsLibrary: "مكتبة الأيقونات",
    channelManager: "مدير القنوات",
    travky: "قناة Travky",
    external: "قناة خارجية",
    guestGroups: "مجموعات الضيوف",
    mealPlans: "خطط الوجبات",
    periods: "الفترات",
    supplements: "الإضافات",
    refundPolicies: "سياسة الاسترداد",
    channelManagerRooms: "أنواع الغرف",
    commission: "العمولة",
    rates: "الأسعار",
    availability: "التوافر",
    stopSale: "إيقاف البيع",
    apiSettings: "إعدادات API",
    // Sidebar – new super-admin sections
    platformFees: "رسوم المنصة",
    platformFeesHotels: "رسوم الفنادق",
    customerServices: "خدمات العملاء",
    manualBooking: "حجز يدوي",
    // Platform Fees – Hotels page
    pfPage_title: "رسوم المنصة - الفنادق",
    pfPage_subtitle: "إدارة رسوم المنصة والحد الأدنى للعمولات",
    pfScope_label: "نطاق التطبيق",
    pfScope_allHotels: "جميع الفنادق",
    pfScope_byCountry: "حسب الدولة",
    pfScope_byCity: "حسب المدينة",
    pfScope_specificHotel: "فندق محدد",
    pfField_platformFee: "% رسوم المنصة",
    pfField_minCommission: "الحد الأدنى للعمولة",
    pfField_minCommissionHint: "الحد الأدنى الذي يمكن للفندق تعيينه كعمولة",
    pfSaved: "تم الحفظ!",
    // Manual Booking page
    mb_pageTitle: "حجز يدوي",
    mb_pageSubtitle: "أنشئ حجزًا نيابةً عن عميل",
    mb_heroSlogan: "احجز تجربتك القادمة",
    mb_tabHotels: "فنادق",
    mb_tabActivities: "أنشطة",
    mb_tabPackages: "باقات",
    mb_country: "الدولة / المنطقة",
    mb_allCountries: "جميع الدول",
    mb_countryEgypt: "مصر",
    mb_countryUAE: "الإمارات",
    mb_countrySaudi: "السعودية",
    mb_checkIn: "تسجيل الدخول",
    mb_checkOut: "تسجيل الخروج",
    mb_roomsGuests: "الغرف والضيوف",
    mb_room: "غرفة",
    mb_rooms: "الغرف",
    mb_adults: "بالغ",
    mb_children: "أطفال",
    mb_searchBtn: "بحث",
    mb_popularDestinations: "وجهات مشهورة",
    mb_popularSubtitle: "أقل الأسعار المقدرة من مستخدمي Travky",
    mb_startingFrom: "يبدأ من",
    mb_bookNow: "احجز الآن",
    hotelPreview: "معاينة الفندق",
    hotelStepMain: "البيانات الأساسية",
    hotelStepDescription: "الوصف",
    hotelStepIcons: "المرافق",
    hotelStepPolicy: "السياسة",
    hotelStepPhotos: "الصور",
    activityMainDetails: "تفاصيل النشاط",
    activityStepMain: "البيانات الأساسية",
    activityStepDescription: "الوصف",
    activityStepIcons: "المرافق",
    activityStepPolicy: "السياسات",
    activityStepPhotos: "الصور",
    unifiedBookingPlatform: "منصة الحجز الموحّدة",
    // Form fields
    basicInfo: "المعلومات الأساسية",
    location: "الموقع",
    contact: "التواصل",
    details: "التفاصيل",
    amenities: "المرافق",
    policies: "السياسات",
    pricing: "التسعير",
    status: "الحالة",
    active: "نشط",
    inactive: "غير نشط",
    description: "الوصف",
    address: "العنوان",
    city: "المدينة",
    country: "الدولة",
    phone: "الهاتف",
    website: "الموقع الإلكتروني",
    type: "النوع",
    stars: "النجوم",
    saving: "جاري الحفظ...",
    // User Form Modal
    createNewUser: "إنشاء مستخدم جديد",
    editUser: "تعديل المستخدم",
    createUser: "إنشاء مستخدم",
    updateUser: "تحديث المستخدم",
    basicInfoTab: "المعلومات الأساسية",
    permissionsTab: "الصلاحيات",
    fullName: "الاسم الكامل",
    emailAddress: "البريد الإلكتروني",
    leaveEmptyPassword: "(اتركه فارغاً للاحتفاظ بالحالي)",
    linkedAdmin: "المدير المرتبط (الشركة)",
    adminRequired: "المدير مطلوب لهذا النوع من الحسابات",
    selectAdmin: "-- اختر مديراً --",
    logoUpload: "صورة الشعار",
    logoPreview: "معاينة الشعار",
    roleDescription: "وصف الدور",
    useCustomPerms: "استخدام صلاحيات مخصصة (تجاوز الافتراضيات)",
    selectAll: "تحديد الكل",
    clearAll: "مسح الكل",
    applyRolePreset: "تطبيق الصلاحيات الافتراضية",
    permissionsSelected: "صلاحية محددة",
    permSummary: "ملخص الصلاحيات",
    noPermsSelected: "لا توجد صلاحيات محددة",
    // Role names & descriptions
    role_super_admin: "مسؤول رئيسي",
    role_admin: "مدير (شركة)",
    role_hotel: "حساب فندق",
    role_restaurant: "حساب مطعم",
    role_activity: "حساب نشاط",
    role_hotel_manager: "مدير فندق",
    role_restaurant_manager: "مدير مطعم",
    role_activity_manager: "مدير نشاط",
    roleDesc_super_admin:
      "وصول كامل لجميع ميزات النظام. يمكنه إدارة جميع المستخدمين والفنادق والمطاعم والأنشطة وإعدادات النظام.",
    roleDesc_admin:
      "مسؤول الشركة. يمكنه إدارة الفنادق والمطاعم والأنشطة التابعة لشركته.",
    roleDesc_hotel:
      "مدير الفندق. يمكنه إدارة الغرف والحجوزات وعرض التقارير الخاصة بفندقه.",
    roleDesc_restaurant:
      "مدير المطعم. يمكنه إدارة الطاولات والحجوزات وعرض تقارير المطعم.",
    roleDesc_activity: "مدير النشاط. يمكنه إدارة الأنشطة والحجوزات الخاصة بها.",
    // Permission modules
    module_users: "إدارة المستخدمين",
    module_admins: "إدارة المدراء",
    module_hotels: "الفنادق",
    module_hotel: "بيانات الفندق",
    module_channel_manager: "مدير القنوات",
    module_channel_manager_travky: "Travky",
    module_channel_manager_external: "خارجي",
    module_guest_groups: "مجموعات النزلاء",
    module_meal_plans: "خطط الوجبات",
    module_periods: "الفترات",
    module_supplements: "الإضافات",
    module_refund_policies: "سياسات الاسترداد",
    module_channel_manager_rooms: "غرف مدير القنوات",
    module_rates: "الأسعار",
    module_availability: "الإتاحة",
    module_restaurants: "المطاعم",
    module_activities: "الأنشطة",
    module_bookings: "الحجوزات",
    module_rooms: "الغرف / الطاولات",
    module_finance: "المالية",
    module_reports: "التقارير",
    module_settings: "الإعدادات",
    // Permission actions
    action_view_users: "عرض المستخدمين",
    action_add_users: "إضافة مستخدمين",
    action_edit_users: "تعديل المستخدمين",
    action_delete_users: "حذف المستخدمين",
    action_view_admins: "عرض المدراء",
    action_add_admins: "إضافة مدراء",
    action_edit_admins: "تعديل المدراء",
    action_delete_admins: "حذف المدراء",
    action_view_hotels: "عرض الفنادق",
    action_add_hotels: "إضافة فنادق",
    action_edit_hotels: "تعديل الفنادق",
    action_delete_hotels: "حذف الفنادق",
    action_view_restaurants: "عرض المطاعم",
    action_add_restaurants: "إضافة مطاعم",
    action_edit_restaurants: "تعديل المطاعم",
    action_delete_restaurants: "حذف المطاعم",
    action_view_activities: "عرض الأنشطة",
    action_add_activities: "إضافة أنشطة",
    action_edit_activities: "تعديل الأنشطة",
    action_delete_activities: "حذف الأنشطة",
    action_view_bookings: "عرض الحجوزات",
    action_add_bookings: "إضافة حجوزات",
    action_edit_bookings: "تعديل الحجوزات",
    action_delete_bookings: "حذف الحجوزات",
    action_view_rooms: "عرض الغرف",
    action_add_rooms: "إضافة غرف",
    action_edit_rooms: "تعديل الغرف",
    action_delete_rooms: "حذف الغرف",
    action_view_finance: "عرض المالية",
    action_add_finance: "إضافة معاملات",
    action_edit_finance: "تعديل المعاملات",
    action_delete_finance: "حذف المعاملات",
    action_view_reports: "عرض التقارير",
    action_view_settings: "عرض الإعدادات",
    action_edit_settings: "تعديل الإعدادات",
    action_details_hotel: "إدارة البيانات الرئيسية للفندق",
    action_view_channel_manager: "عرض مدير القنوات",
    action_view_channel_manager_travky: "عرض Travky",
    action_view_channel_manager_external: "عرض القنوات الخارجية",
    action_view_guest_groups: "عرض مجموعات النزلاء",
    action_view_meal_plans: "عرض خطط الوجبات",
    action_view_periods: "عرض الفترات",
    action_view_supplements: "عرض الإضافات",
    action_view_refund_policies: "عرض سياسات الاسترداد",
    action_view_channel_manager_rooms: "عرض غرف مدير القنوات",
    action_view_rates: "عرض الأسعار",
    action_view_availability: "عرض الإتاحة",
    dangerLabel: "خطر",
    allLabel: "الكل",
    // Admins page
    adminsManagement: "إدارة المدراء",
    adminsSubtitle: "مسؤولو الشركات — يديرون الفنادق والمطاعم والأنشطة",
    addAdmin: " إضافة مدير",
    totalAdmins: "إجمالي المدراء",
    withPermissions: "لديهم صلاحيات",
    managedAccounts: "الحسابات المُدارة",
    editAdmin: "تعديل المدير",
    areYouSureDeleteAdmin: "هل أنت متأكد من حذف هذا المدير؟",
    loadingAdmins: "جاري تحميل المدراء...",
    errorLoadingAdmins: "خطأ في تحميل المدراء",
    permissionsLabel: "الصلاحيات",
    moreLabel: "المزيد",
    // Hotels page
    hotelAccounts: "حسابات الفنادق",
    hotelAccountsSubtitle:
      "إدارة حسابات مستخدمي الفنادق — يجب ربط كل حساب بمدير",
    addHotelAccount: " إضافة حساب فندق",
    linkedToAdmin: "مرتبط بمدير",
    noAdminLinked: "بلا مدير",
    noAdminWarning: "بلا مدير",
    loadingHotelAccounts: "جاري تحميل حسابات الفنادق...",
    errorLoadingData: "خطأ في تحميل البيانات",
    hotelAccountsTable: "جميع حسابات الفنادق (عرض الجدول)",
    areYouSureDeleteHotelAccount: "هل أنت متأكد من حذف حساب الفندق هذا؟",
    noHotelAccountsYet:
      'لا توجد حسابات فنادق بعد. انقر على "+ إضافة حساب فندق" لإنشاء واحد.',
    adminRequiredForHotelTitle: "مطلوب حساب مدير",
    adminRequiredForHotelMessage:
      "لا يمكنك إضافة حساب فندق قبل إنشاء مدير واحد على الأقل. أنشئ مديراً أولاً ثم أكمل إضافة الفندق.",
    createAdminNow: "إضافة مدير الآن",
    // SuperAdmin dashboard
    superAdminOverview: "نظرة عامة على المدير الرئيسي",
    managePlatformResources: "إدارة جميع موارد المنصة من هنا.",
    superAdminUsers: "مستخدمو المدير الرئيسي",
    adminDashboardTitle: "لوحة تحكم شركة الإدارة",
    adminDashboardSubtitle:
      "عرض الفنادق والمطاعم والأنشطة والعمليات من لوحة تحكم للعرض فقط.",
    // Table column labels
    guest: "الضيف",
    checkIn: "تسجيل الوصول",
    checkOut: "تسجيل المغادرة",
    capacity: "السعة",
    roomTableNum: "رقم الغرفة/الطاولة",
    date: "التاريخ",
    revenue: "الإيرادات",
    expenses: "المصروفات",
    reportTitle: "التقرير",
    generatedAt: "تاريخ الإنشاء",
    // Reports page
    reportsSubtitle: "تقارير مبنية على الحجوزات مجمّعة حسب النوع والشهر.",
    reportName: "التقرير",
    reportType: "النوع",
    reportPeriod: "الفترة",
    reportPeriodAllTime: "الكل",
    reportGenerated: "تاريخ الإنشاء",
    reportStatus: "الحالة",
    reportReady: "جاهز",
    reportProcessing: "قيد المعالجة",
    reportTotal: "إجمالي التقارير",
    reportThisMonth: "هذا الشهر",
    reportNoRecords: "لا توجد تقارير بعد. ستُنشئ الحجوزات تقارير تلقائياً.",
    reportTypeMonthly: "شهري",
    reportTypeBookings: "الحجوزات",
    reportTypeStatus: "الحالة",
    loadingReportsData: "جاري تحميل التقارير...",
    errorLoadingReports: "خطأ في تحميل التقارير",
    // Permission action labels
    view: "عرض",
    manage: "إدارة",
    // Rooms page
    roomsPage_totalRooms: "إجمالي الغرف",
    roomsPage_available: "متاح",
    roomsPage_occupied: "مشغول",
    roomsPage_maintenance: "صيانة",
    roomsPage_reserved: "محجوز",
    roomsPage_searchPlaceholder: "البحث في الغرف...",
    roomsPage_allStatuses: "جميع الحالات",
    roomsPage_addRoom: "+ إضافة غرفة",
    roomsPage_noRooms: "لا توجد غرف",
    roomsPage_guests: "ضيوف",
    roomsPage_deleteRoomTitle: "حذف الغرفة #",
    roomsPage_deleteCannotUndo: "لا يمكن التراجع عن هذا الإجراء.",
    // Bookings page
    bkPage_totalBookings: "إجمالي الحجوزات",
    bkPage_confirmed: "مؤكد",
    bkPage_checkedIn: "تسجيل وصول",
    bkPage_pendingPayment: "دفع معلق",
    bkPage_searchPlaceholder: "البحث بالاسم أو المرجع أو الغرفة...",
    bkPage_allStatuses: "جميع الحالات",
    bkPage_allPayments: "جميع المدفوعات",
    bkPage_newBooking: "+ حجز جديد",
    bkPage_noBookings: "لا توجد حجوزات",
    bkPage_colRef: "الرقم المرجعي",
    bkPage_colGuest: "الضيف",
    bkPage_colRoom: "الغرفة",
    bkPage_colCheckIn: "تسجيل الوصول",
    bkPage_colCheckOut: "تسجيل المغادرة",
    bkPage_colTotal: "الإجمالي",
    bkPage_colStatus: "الحالة",
    bkPage_colPayment: "الدفع",
    bkPage_deleteBookingTitle: "حذف الحجز؟",
    // Room form modal
    rm_addTitle: "إضافة غرفة جديدة",
    rm_editTitle: "تعديل الغرفة",
    rm_subtitle: "أدخل تفاصيل الغرفة أدناه",
    rm_tabBasic: "أساسي",
    rm_tabPricing: "التسعير",
    rm_tabAmenities: "المرافق",
    rm_tabPhotos: "الصور",
    rm_secIdentity: "هوية الغرفة",
    rm_secCapacity: "السعة والأسرّة",
    rm_secFeatures: "مميزات الغرفة",
    rm_secPricingDetails: "تفاصيل التسعير",
    rm_secAmenities: "مرافق الغرفة",
    rm_secPhotos: "صور الغرفة",
    rm_fieldNumber: "رقم الغرفة / الطاولة *",
    rm_fieldName: "اسم الغرفة",
    rm_fieldType: "النوع",
    rm_fieldCategory: "الفئة",
    rm_fieldFloor: "الطابق",
    rm_fieldStatus: "الحالة",
    rm_fieldGuests: "الضيوف",
    rm_fieldBeds: "الأسرّة",
    rm_fieldBedType: "نوع السرير",
    rm_fieldBathrooms: "الحمامات",
    rm_fieldSize: "المساحة (م²)",
    rm_fieldView: "الإطلالة",
    rm_fieldSmoking: "التدخين مسموح",
    rm_fieldPets: "الحيوانات الأليفة مسموحة",
    rm_fieldDesc: "الوصف",
    rm_descPlaceholder: "صف تجربة الغرفة...",
    rm_fieldPrice: "السعر لكل ليلة *",
    rm_fieldCurrency: "العملة",
    rm_fieldDiscount: "الخصم (%)",
    rm_pricingSummary: "ملخص التسعير",
    rm_basePrice: "السعر الأساسي / ليلة",
    rm_finalPrice: "السعر النهائي / ليلة",
    rm_perWeek: "لكل أسبوع (7 ليالٍ)",
    rm_perMonth: "لكل شهر (30 ليلة)",
    rm_typeRoom: "غرفة",
    rm_typeSuite: "جناح",
    rm_typeStudio: "استوديو",
    rm_typeVilla: "فيلا",
    rm_typeTable: "طاولة (مطعم)",
    rm_typeService: "خدمة / أخرى",
    rm_catStandard: "عادي",
    rm_catDeluxe: "ديلكس",
    rm_catSuperior: "سوبريور",
    rm_catExecutive: "إكزيكيوتيف",
    rm_catPresidential: "رئاسي",
    rm_statusAvailable: "متاح",
    rm_statusOccupied: "مشغول",
    rm_statusReserved: "محجوز",
    rm_statusMaintenance: "صيانة",
    rm_bedSingle: "سرير مفرد",
    rm_bedDouble: "سرير مزدوج",
    rm_bedQueen: "كوين",
    rm_bedKing: "كينج",
    rm_bedTwin: "توين",
    rm_bedSofa: "سرير أريكة",
    rm_viewNone: "لا إطلالة محددة",
    rm_viewSea: "إطلالة بحرية",
    rm_viewPool: "إطلالة على المسبح",
    rm_viewCity: "إطلالة على المدينة",
    rm_viewGarden: "إطلالة على الحديقة",
    rm_viewMountain: "إطلالة على الجبل",
    rm_amenityIncluded: "مضمّن",
    rm_amenityNotIncluded: "غير مضمّن",
    rm_amenityToggleHint: "انقر للتبديل",
    rm_photosUploadHint: "انقر أو اسحب الصور هنا",
    rm_photosLimit: "حتى 8 صور — JPEG / PNG / WebP",
    rm_photoMain: "رئيسي",
    rm_photoSetMain: "رئيسي",
    rm_errNumber: "رقم الغرفة / الطاولة مطلوب.",
    rm_errPrice: "سعر الليلة مطلوب.",
    rm_errSave: "فشل في حفظ الغرفة.",
    rm_addBtn: "إضافة غرفة",
    rm_updateBtn: "تحديث الغرفة",
    // Booking form modal
    bk_addTitle: "حجز جديد",
    bk_editTitle: "تعديل الحجز",
    bk_tabGuest: "الضيف",
    bk_tabStay: "الإقامة",
    bk_tabPayment: "الدفع",
    bk_tabNotes: "ملاحظات",
    bk_secGuestInfo: "معلومات الضيف",
    bk_secGuestCount: "عدد الضيوف",
    bk_secStay: "تفاصيل الإقامة",
    bk_secRoom: "تعيين الغرفة",
    bk_secPayment: "تفاصيل الدفع",
    bk_secNotes: "الطلبات والملاحظات",
    bk_fieldName: "الاسم الكامل *",
    bk_fieldEmail: "البريد الإلكتروني",
    bk_fieldPhone: "رقم الهاتف",
    bk_fieldNationality: "الجنسية",
    bk_fieldSource: "مصدر الحجز",
    bk_fieldAdults: "البالغون",
    bk_fieldChildren: "الأطفال",
    bk_srcDirect: "مباشر",
    bk_srcOnline: "إلكتروني",
    bk_srcPhone: "هاتف",
    bk_srcWalkIn: "حضور مباشر",
    bk_srcAgency: "وكالة",
    bk_fieldBookingType: "نوع الحجز",
    bk_fieldBookingStatus: "حالة الحجز",
    bk_fieldCheckIn: "تاريخ تسجيل الوصول *",
    bk_fieldCheckOut: "تاريخ تسجيل المغادرة *",
    bk_typeHotel: "فندق",
    bk_typeRestaurant: "مطعم",
    bk_typeActivity: "نشاط",
    bk_statusPending: "قيد الانتظار",
    bk_statusConfirmed: "مؤكد",
    bk_statusCheckedIn: "تسجيل وصول",
    bk_statusCheckedOut: "تسجيل مغادرة",
    bk_statusCancelled: "ملغي",
    bk_statusNoShow: "لم يحضر",
    bk_night: "ليلة",
    bk_nights: "ليالٍ",
    bk_duration: "المدة",
    bk_fieldSelectRoom: "اختر الغرفة",
    bk_noRoomAssigned: "لا توجد غرفة محددة",
    bk_fieldPricePerNight: "السعر لكل ليلة",
    bk_fieldPaymentMethod: "طريقة الدفع",
    bk_fieldPaymentStatus: "حالة الدفع",
    bk_fieldDiscount: "الخصم (%)",
    bk_fieldTaxRate: "نسبة الضريبة (%)",
    bk_fieldPaid: "المبلغ المدفوع",
    bk_pmCash: "نقداً",
    bk_pmCard: "بطاقة ائتمانية / مدى",
    bk_pmBank: "تحويل بنكي",
    bk_pmOnline: "إلكتروني",
    bk_pmOther: "أخرى",
    bk_psUnpaid: "غير مدفوع",
    bk_psPartial: "مدفوع جزئياً",
    bk_psPaid: "مدفوع بالكامل",
    bk_psRefunded: "مُسترجع",
    bk_summaryTitle: "ملخص الحجز",
    bk_summaryNightsRate: "الليالي × المعدل",
    bk_summarySubtotal: "المجموع الفرعي",
    bk_summaryDiscount: "الخصم",
    bk_summaryTax: "الضريبة",
    bk_summaryTotal: "الإجمالي",
    bk_summaryPaid: "المدفوع",
    bk_summaryBalance: "المبلغ المتبقي",
    bk_fieldSpecialReq: "طلبات خاصة (من الضيف)",
    bk_fieldGuestNotes: "ملاحظات الضيف",
    bk_fieldInternalNotes: "ملاحظات داخلية (للموظفين فقط)",
    bk_fieldSpecialReqPlaceholder:
      "مثلاً: طابق عالٍ، وسائد إضافية، تزيين لمناسبة...",
    bk_fieldGuestNotesPlaceholder: "أي ملاحظات إضافية من الضيف...",
    bk_fieldInternalNotesPlaceholder:
      "ملاحظات داخلية للموظفين (لا تظهر للضيوف)...",
    bk_errName: "اسم العميل مطلوب.",
    bk_errCheckIn: "تاريخ تسجيل الوصول مطلوب.",
    bk_errCheckOut: "تاريخ تسجيل المغادرة مطلوب.",
    bk_errDates: "يجب أن يكون تسجيل المغادرة بعد تسجيل الوصول.",
    bk_errSave: "فشل في حفظ الحجز.",
    bk_confirmBtn: "تأكيد الحجز",
    bk_updateBtn: "تحديث الحجز",
    bk_footerTotal: "الإجمالي",
    // Dashboard shared keys
    dashboardWelcomeLine: "مرحباً بعودتك،",
    dashboardPlatformOverview: "إليك نظرة عامة على منصتك.",
    dashboardBusinessOverview: "إليك ما يحدث في نشاطك التجاري اليوم.",
    // Dashboard stat card titles
    dashboardCardPlatformRevenue: "إيرادات المنصة",
    dashboardCardAdminAccounts: "حسابات المدراء",
    dashboardCardTotalBookings: "إجمالي الحجوزات",
    dashboardCardManagedEntities: "الجهات المُدارة",
    dashboardCardTotalRevenue: "إجمالي الإيرادات",
    dashboardCardManagedAccounts: "الحسابات المُدارة",
    dashboardCardTeamMembers: "أعضاء الفريق",
    dashboardCardAvailableRooms: "الغرف المتاحة",
    dashboardCardActivities: "الأنشطة المدرجة",
    dashboardCardAvailableTables: "الطاولات المتاحة",
    dashboardCardTotalReservations: "إجمالي الحجوزات",
    // Dashboard donut chart segments
    dashboardSegmentHotels: "الفنادق",
    dashboardSegmentRestaurants: "المطاعم",
    dashboardSegmentActivities: "الأنشطة",
    dashboardSegmentAdmins: "المدراء",
    dashboardSegmentConfirmed: "مؤكد",
    dashboardSegmentPending: "قيد الانتظار",
    dashboardSegmentCheckedIn: "تسجيل وصول",
    dashboardSegmentCancelled: "ملغي",
    dashboardSegmentSeated: "جالس",
    // Dashboard donut chart titles
    dashboardEntityDistribution: "توزيع الجهات",
    dashboardEntityDistributionSubtitle: "توزيع حسب نوع الحساب المُدار",
    dashboardAccountTypes: "توزيع الحسابات",
    dashboardAccountTypesSubtitle: "توزيع حسب نوع الحساب",
    dashboardBookingStatus: "حالة الحجوزات",
    dashboardBookingStatusSubtitle: "توزيع الحجوزات حسب الحالة",
    dashboardReservationStatus: "حالة الحجوزات",
    dashboardReservationStatusSubtitle: "توزيع الحجوزات حسب الحالة",
    dashboardTotalLabel: "الإجمالي",
    dashboardVisitsLabel: "الإجمالي",
    // Dashboard overview chart
    dashboardTabRevenue: "الإيرادات",
    dashboardTabOrders: "الطلبات",
    dashboardTabProfit: "الأرباح",
    dashboardTabBookings: "الحجوزات",
    dashboardTabReservations: "الحجوزات",
    dashboardOverviewTitle: "نظرة عامة على الإيرادات",
    dashboardOverviewSubtitle: "الأداء الشهري — الإيرادات والحجوزات والأرباح",
    // Dashboard monthly goals
    dashboardMonthlyGoalsTitle: "الأهداف الشهرية",
    dashboardMonthlyGoalsSubtitle: "التقدم نحو أهداف هذا الشهر",
    dashboardNoGoals: "لم يتم إعداد أهداف",
    // Dashboard goal labels
    dashboardGoalPlatformRevenue: "إيرادات المنصة",
    dashboardGoalBookings: "إجمالي الحجوزات",
    dashboardGoalManagedEntities: "الجهات المُدارة",
    dashboardGoalRevenue: "هدف الإيرادات",
    dashboardGoalManagedAccounts: "الحسابات المُدارة",
    dashboardGoalOccupancyRate: "نسبة الإشغال",
    dashboardGoalReservations: "هدف الحجوزات",
    dashboardGoalTableUtilization: "استخدام الطاولات",
    dashboardGoalActivitiesListed: "الأنشطة المدرجة",
    // DataModal labels (AR)
    dataModal_manage: "إدارة البيانات",
    dataModal_title: "إدارة البيانات",
    dataModal_export: "تصدير البيانات",
    dataModal_exportDesc: "تنزيل كافة السجلات كملف .xlsx",
    dataModal_import: "استيراد البيانات",
    dataModal_importDesc: "رفع ملف .xlsx لإضافة سجلات مجمعة",
    dataModal_template: "تنزيل القالب",
    dataModal_templateDesc: "احصل على قالب إكسل فارغ لتعبئته",
    dataModal_exporting: "جاري التصدير...",
    dataModal_exportSuccess: "تم تصدير البيانات بنجاح!",
    dataModal_exportError: "فشل التصدير. يرجى المحاولة مرة أخرى.",
    dataModal_downloading: "جاري تنزيل القالب...",
    dataModal_templateSuccess: "تم تنزيل القالب!",
    dataModal_templateError: "فشل التنزيل. يرجى المحاولة مرة أخرى.",
    dataModal_importing: "جاري الاستيراد...",
    dataModal_importSuccess: "اكتمل الاستيراد!",
    dataModal_rowsImported: "سجل تم استيراده",
    dataModal_importError: "فشل الاستيراد.",
    // Refund Policies page
    rp_title: "سياسات الاسترداد",
    rp_subtitle: "تحديد قواعد الإلغاء والاسترداد",
    rp_policyType: "نوع السياسة",
    rp_daysBeforeArrival: "أيام قبل الوصول",
    rp_fees: "الرسوم",
    rp_extraPrice: "سعر إضافي",
    rp_extraPriceHint: "سعر إضافي يُضاف فوق سعر الغرفة لهذه الخطة",
    rp_noData: "لا توجد سياسات استرداد بعد",
    rp_days: "أيام",
    rp_day: "يوم",
    rp_30day: "30 يوم",
    rp_1day: "1 يوم",
    rp_typeNonRefundable: "غير قابل للاسترداد",
    rp_typeFreeCancellation: "إلغاء مجاني",
    rp_typePartial: "جزئي",
    rp_viewTitle: "عرض سياسة الاسترداد",
    rp_editTitle: "تعديل السياسة",
    rp_addTitle: "إضافة سياسة استرداد",
    rp_fieldName: "الاسم",
    rp_fieldFeesPercent: "نسبة الرسوم (%)",
    rp_feeCalcMethod: "طريقة احتساب الرسوم",
    rp_fixedAmount: "مبلغ ثابت",
    rp_percentage: "نسبة مئوية",
    rp_fixedPerGroup: "مبلغ ثابت لكل مجموعة",
    rp_nameRequired: "الاسم مطلوب",
    // Periods page
    per_title: "الفترات الزمنية",
    per_subtitle: "تحديد فترات المواسم والأسعار",
    per_fieldName: "الاسم",
    per_fieldFrom: "من",
    per_fieldTo: "إلى",
    per_noData: "لا توجد فترات زمنية بعد",
    per_viewTitle: "عرض الفترة الزمنية",
    per_editTitle: "تعديل الفترة الزمنية",
    per_addTitle: "إضافة فترة زمنية",
    per_nameRequired: "الاسم مطلوب",
    per_fromRequired: "تاريخ البداية مطلوب",
    per_toRequired: "تاريخ النهاية مطلوب",
    per_toAfterFrom: "يجب أن يكون تاريخ النهاية بعد البداية",
    // Commission page
    comm_subtitle: "{{count}} عمولة مضافة",
    comm_addBtn: "إضافة عمولة",
    comm_viewTitle: "تفاصيل العمولة",
    comm_editTitle: "تعديل العمولة",
    comm_addTitle: "إضافة عمولة",
    comm_fieldName: "اسم العمولة",
    comm_fieldType: "نوع العمولة",
    comm_fieldValue: "القيمة",
    comm_fieldValuePercent: "القيمة (%)",
    comm_fieldValueFixed: "القيمة (مبلغ ثابت)",
    comm_fieldAppliesTo: "تطبق على",
    comm_fieldNotes: "ملاحظات",
    comm_namePlaceholder: "مثال: عمولة وكلاء السفر",
    comm_notesPlaceholder: "ملاحظات إضافية...",
    comm_nameRequired: "اسم العمولة مطلوب",
    comm_valueRequired: "قيمة العمولة يجب أن تكون رقماً موجباً",
    comm_active: "نشط",
    comm_inactive: "غير نشط",
    comm_deactivate: "إيقاف تشغيل",
    comm_activate: "تشغيل",
    comm_fixed: "ثابت",
    comm_noData: "لا توجد عمولات مضافة",
    comm_saveChanges: "حفظ التعديلات",
    comm_pageTitle: "العمولة",
    comm_pageSubtitle: "تحديد الحد الأدنى لعمولة المنصة من الحجوزات",
    comm_b2cTitle: "B2C",
    comm_b2cSubtitle: "عمولة الحجوزات للعملاء المباشرين",
    comm_b2bTitle: "B2B",
    comm_b2bSubtitle: "عمولة الحجوزات بين الشركات",
    comm_platformFees: "Platform Fees",
    comm_minLabel: "الحد الأدنى للعمولة",
    comm_totalLabel: "الإجمالي",
    comm_formulaNote: "المعادلة: رسوم المنصة + الحد الأدنى للعمولة = الإجمالي. رسوم المنصة قيمة ثابتة لا يمكنك تغييرها.",
    comm_next: "التالي",
    comm_saved: "تم الحفظ!",
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem("lang") || "en");
  const [theme, setTheme] = useState(
    () => localStorage.getItem("theme") || "light",
  );

  useEffect(() => {
    localStorage.setItem("lang", lang);
    document.documentElement.dir = translations[lang].dir;
    document.documentElement.lang = lang;
  }, [lang]);

  useEffect(() => {
    localStorage.setItem("theme", theme);
    if (theme === "dark") {
      document.documentElement.classList.add("dark");
    } else {
      document.documentElement.classList.remove("dark");
    }
  }, [theme]);

  const toggleLang = () => setLang((l) => (l === "en" ? "ar" : "en"));
  const toggleTheme = () => setTheme((t) => (t === "light" ? "dark" : "light"));

  const t = (key, params) => {
    const template = translations[lang][key] || key;
    if (!params) return template;

    return Object.entries(params).reduce((result, [paramKey, value]) => {
      return result.replaceAll(`{{${paramKey}}}`, String(value ?? ""));
    }, template);
  };

  return (
    <LanguageContext.Provider
      value={{
        lang,
        toggleLang,
        t,
        dir: translations[lang].dir,
        theme,
        toggleTheme,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
