import { createContext, useContext, useState, useEffect } from "react";

const translations = {
  en: {
    dir: "ltr",
    // Login page
    welcomeBack: "Welcome back",
    loginSubtext: "Manage bookings across hotels, restaurants, and activities.",
    signInToContinue: "Sign in to continue",
    unifiedPlatform: "Unified Booking Platform",
    controlBooking: "Control every booking",
    inOnePlace: " in one place",
    fiveDesc:
      "Five dashboards for super admin, admin company, hotels, restaurants, and activities. Role-based access, permissions-aware sidebar, and real-time data.",
    security: "Security",
    dashboards: "Dashboards",
    tailoredViews: "5 tailored views",
    emailPlaceholder: "Email",
    passwordPlaceholder: "Password",
    loginBtn: "Login",
    signingIn: "Signing in...",
    sampleAccounts: "Sample accounts",
    loginFailed: "Login Failed",
    invalidCredentials:
      "Invalid credentials. Please check your email and password.",
    tryAgain: "Try Again",
    // Nav / General
    dashboard: "Dashboard",
    settings: "Settings",
    logout: "Logout",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    search: "Search",
    close: "Close",
    loading: "Loading...",
    error: "Error",
    noData: "No data found",
    featured: "FEATURED",
    actions: "Actions",
    exportCsv: "Export CSV",
    // Hotels
    hotelsManagement: "Hotels Management",
    addHotel: "+ Add Hotel",
    editHotel: "Edit Hotel",
    createHotel: "Create Hotel",
    updateHotel: "Update Hotel",
    deleteHotelConfirm: "Are you sure you want to delete this hotel?",
    errorLoadingHotels: "Error loading hotels. Please check your connection.",
    perNight: "/ night",
    // Restaurants
    restaurantsManagement: "Restaurants Management",
    addRestaurant: "+ Add Restaurant",
    editRestaurant: "Edit Restaurant",
    createRestaurant: "Create Restaurant",
    updateRestaurant: "Update Restaurant",
    deleteRestaurantConfirm: "Are you sure you want to delete this restaurant?",
    errorLoadingRestaurants: "Error loading restaurants.",
    avgPrice: "Avg price",
    // Activities
    activitiesManagement: "Activities Management",
    addActivity: "+ Add Activity",
    editActivity: "Edit Activity",
    createActivity: "Create Activity",
    updateActivity: "Update Activity",
    deleteActivityConfirm: "Are you sure you want to delete this activity?",
    errorLoadingActivities: "Error loading activities.",
    duration: "Duration",
    price: "Price",
    // Settings
    settingsTitle: "Settings",
    settingsSubtitle: "Manage your account and preferences.",
    theme: "Theme",
    lightMode: "Light Mode",
    darkMode: "Dark Mode",
    emailNotificationsLabel: "Email Notifications",
    comingSoonLabel: "Coming soon",
    profile: "Profile",
    name: "Name",
    email: "Email",
    role: "Role",
    preferences: "Preferences",
    language: "Language",
    emailNotifications: "Email Notifications",
    comingSoon: "Coming soon",
    permissions: "Permissions",
    noPermissions: "No explicit permissions (inherited from role)",
    // Sidebar items
    users: "Users",
    admins: "Admins",
    allHotels: "All Hotels",
    allRestaurants: "All Restaurants",
    allActivities: "All Activities",
    allBookings: "All Bookings",
    roomsTables: "Rooms/Tables",
    finance: "Finance",
    reports: "Reports",
    unifiedBookingPlatform: "Unified Booking Platform",
    // Form fields
    basicInfo: "Basic Information",
    location: "Location",
    contact: "Contact",
    details: "Details",
    amenities: "Amenities",
    policies: "Policies",
    pricing: "Pricing",
    status: "Status",
    active: "Active",
    inactive: "Inactive",
    description: "Description",
    address: "Address",
    city: "City",
    country: "Country",
    phone: "Phone",
    website: "Website",
    type: "Type",
    stars: "Stars",
    saving: "Saving...",
    // User Form Modal
    createNewUser: "Create New User",
    editUser: "Edit User",
    createUser: "Create User",
    updateUser: "Update User",
    basicInfoTab: "Basic Info",
    permissionsTab: "Permissions",
    fullName: "Full Name",
    emailAddress: "Email Address",
    leaveEmptyPassword: "(leave empty to keep current)",
    linkedAdmin: "Linked Admin (Company)",
    adminRequired: "Admin is required for this account type",
    selectAdmin: "-- Select Admin --",
    logoUpload: "Logo Image",
    logoPreview: "Logo preview",
    roleDescription: "Role Description",
    useCustomPerms: "Use custom permissions (override role defaults)",
    selectAll: "Select All",
    clearAll: "Clear All",
    applyRolePreset: "Apply Role Preset",
    permissionsSelected: "permissions selected",
    permSummary: "Permission Summary",
    noPermsSelected: "No permissions selected",
    // Role names & descriptions
    role_super_admin: "Super Admin",
    role_admin: "Admin (Company)",
    role_hotel: "Hotel Account",
    role_restaurant: "Restaurant Account",
    role_activity: "Activity Account",
    role_hotel_manager: "Hotel Manager",
    role_restaurant_manager: "Restaurant Manager",
    role_activity_manager: "Activity Manager",
    roleDesc_super_admin:
      "Full access to all system features. Can manage all users, hotels, restaurants, activities, and system settings.",
    roleDesc_admin:
      "Company administrator. Can manage hotels, restaurants, and activities under their company.",
    roleDesc_hotel:
      "Hotel manager. Can manage rooms, bookings, and view reports for their hotel.",
    roleDesc_restaurant:
      "Restaurant manager. Can manage tables, reservations, and view reports for their restaurant.",
    roleDesc_activity:
      "Activity manager. Can manage activities and bookings for their activities.",
    // Permission modules
    module_users: "Users Management",
    module_hotels: "Hotels",
    module_restaurants: "Restaurants",
    module_activities: "Activities",
    module_bookings: "Bookings",
    module_rooms: "Rooms / Tables",
    module_finance: "Finance",
    module_reports: "Reports",
    module_settings: "Settings",
    // Permission actions
    action_view_users: "View Users",
    action_add_users: "Add Users",
    action_edit_users: "Edit Users",
    action_delete_users: "Delete Users",
    action_view_hotels: "View Hotels",
    action_add_hotels: "Add Hotels",
    action_edit_hotels: "Edit Hotels",
    action_delete_hotels: "Delete Hotels",
    action_view_restaurants: "View Restaurants",
    action_add_restaurants: "Add Restaurants",
    action_edit_restaurants: "Edit Restaurants",
    action_delete_restaurants: "Delete Restaurants",
    action_view_activities: "View Activities",
    action_add_activities: "Add Activities",
    action_edit_activities: "Edit Activities",
    action_delete_activities: "Delete Activities",
    action_view_bookings: "View Bookings",
    action_add_bookings: "Add Bookings",
    action_edit_bookings: "Edit Bookings",
    action_delete_bookings: "Delete Bookings",
    action_view_rooms: "View Rooms",
    action_add_rooms: "Add Rooms",
    action_edit_rooms: "Edit Rooms",
    action_delete_rooms: "Delete Rooms",
    action_view_finance: "View Finance",
    action_add_finance: "Add Transactions",
    action_edit_finance: "Edit Transactions",
    action_delete_finance: "Delete Transactions",
    action_view_reports: "View Reports",
    action_view_settings: "View Settings",
    action_edit_settings: "Edit Settings",
    dangerLabel: "DANGER",
    allLabel: "All",
    // Admins page
    adminsManagement: "Admins Management",
    adminsSubtitle:
      "Company administrators — manage hotels, restaurants & activities",
    addAdmin: "+ Add Admin",
    totalAdmins: "Total Admins",
    withPermissions: "With Permissions",
    managedAccounts: "Managed Accounts",
    editAdmin: "Edit Admin",
    areYouSureDeleteAdmin: "Are you sure you want to delete this admin?",
    loadingAdmins: "Loading admins...",
    errorLoadingAdmins: "Error loading admins",
    permissionsLabel: "Permissions",
    moreLabel: "more",
    // Hotels page
    hotelAccounts: "Hotel Accounts",
    hotelAccountsSubtitle:
      "Manage hotel user accounts — each must be linked to an Admin",
    addHotelAccount: "+ Add Hotel Account",
    linkedToAdmin: "Linked to Admin",
    noAdminLinked: "No Admin Linked",
    noAdminWarning: "NO ADMIN",
    loadingHotelAccounts: "Loading hotel accounts...",
    errorLoadingData: "Error loading data",
    hotelAccountsTable: "All Hotel Accounts (Table View)",
    areYouSureDeleteHotelAccount:
      "Are you sure you want to delete this hotel account?",
    noHotelAccountsYet:
      'No hotel accounts yet. Click "+ Add Hotel Account" to create one.',
    // SuperAdmin dashboard
    superAdminOverview: "Super Admin Overview",
    managePlatformResources: "Manage all platform resources from here.",
    superAdminUsers: "Super Admin Users",
    bookings: "Bookings",
    // Table column labels
    guest: "Guest",
    checkIn: "Check-in",
    checkOut: "Check-out",
    capacity: "Capacity",
    roomTableNum: "Room/Table #",
    date: "Date",
    revenue: "Revenue",
    expenses: "Expenses",
    reportTitle: "Report",
    generatedAt: "Generated",
  },
  ar: {
    dir: "rtl",
    // Login page
    welcomeBack: "مرحباً بك",
    loginSubtext: "إدارة الحجوزات عبر الفنادق والمطاعم والأنشطة.",
    signInToContinue: "سجّل دخولك للمتابعة",
    unifiedPlatform: "منصة الحجز الموحّدة",
    controlBooking: "تحكّم في كل حجز",
    inOnePlace: " في مكان واحد",
    fiveDesc:
      "خمس لوحات تحكم للمسؤول الرئيسي وشركة الإدارة والفنادق والمطاعم والأنشطة. وصول قائم على الأدوار وشريط جانبي وبيانات فورية.",
    security: "الأمان",
    dashboards: "لوحات التحكم",
    tailoredViews: "5 طرق عرض مخصصة",
    emailPlaceholder: "البريد الإلكتروني",
    passwordPlaceholder: "كلمة المرور",
    loginBtn: "تسجيل الدخول",
    signingIn: "جاري تسجيل الدخول...",
    sampleAccounts: "حسابات تجريبية",
    loginFailed: "فشل تسجيل الدخول",
    invalidCredentials:
      "بيانات غير صحيحة. يرجى التحقق من البريد الإلكتروني وكلمة المرور.",
    tryAgain: "حاول مرة أخرى",
    // Nav / General
    dashboard: "لوحة التحكم",
    settings: "الإعدادات",
    logout: "تسجيل الخروج",
    save: "حفظ",
    cancel: "إلغاء",
    delete: "حذف",
    edit: "تعديل",
    add: "إضافة",
    search: "بحث",
    close: "إغلاق",
    loading: "جاري التحميل...",
    error: "خطأ",
    noData: "لا توجد بيانات",
    featured: "مميز",
    actions: "إجراءات",
    exportCsv: "تصدير CSV",
    // Hotels
    hotelsManagement: "إدارة الفنادق",
    addHotel: "+ إضافة فندق",
    editHotel: "تعديل الفندق",
    createHotel: "إنشاء فندق",
    updateHotel: "تحديث الفندق",
    deleteHotelConfirm: "هل أنت متأكد من حذف هذا الفندق؟",
    errorLoadingHotels: "خطأ في تحميل الفنادق. يرجى التحقق من الاتصال.",
    perNight: "/ ليلة",
    // Restaurants
    restaurantsManagement: "إدارة المطاعم",
    addRestaurant: "+ إضافة مطعم",
    editRestaurant: "تعديل المطعم",
    createRestaurant: "إنشاء مطعم",
    updateRestaurant: "تحديث المطعم",
    deleteRestaurantConfirm: "هل أنت متأكد من حذف هذا المطعم؟",
    errorLoadingRestaurants: "خطأ في تحميل المطاعم.",
    avgPrice: "متوسط السعر",
    // Activities
    activitiesManagement: "إدارة الأنشطة",
    addActivity: "+ إضافة نشاط",
    editActivity: "تعديل النشاط",
    createActivity: "إنشاء نشاط",
    updateActivity: "تحديث النشاط",
    deleteActivityConfirm: "هل أنت متأكد من حذف هذا النشاط؟",
    errorLoadingActivities: "خطأ في تحميل الأنشطة.",
    duration: "المدة",
    price: "السعر",
    // Settings
    settingsTitle: "الإعدادات",
    settingsSubtitle: "إدارة حسابك وتفضيلاتك.",
    theme: "المظهر",
    lightMode: "وضع نهاري",
    darkMode: "وضع ليلي",
    emailNotificationsLabel: "إشعارات البريد الإلكتروني",
    comingSoonLabel: "قريباً",
    profile: "الملف الشخصي",
    name: "الاسم",
    email: "البريد الإلكتروني",
    role: "الدور",
    preferences: "التفضيلات",
    language: "اللغة",
    emailNotifications: "إشعارات البريد الإلكتروني",
    comingSoon: "قريباً",
    permissions: "الصلاحيات",
    noPermissions: "لا توجد صلاحيات محددة (موروثة من الدور)",
    // Sidebar items
    users: "المستخدمون",
    admins: "المدراء",
    allHotels: "جميع الفنادق",
    allRestaurants: "جميع المطاعم",
    allActivities: "جميع الأنشطة",
    allBookings: "جميع الحجوزات",
    roomsTables: "الغرف / الطاولات",
    finance: "المالية",
    reports: "التقارير",
    unifiedBookingPlatform: "منصة الحجز الموحّدة",
    // Form fields
    basicInfo: "المعلومات الأساسية",
    location: "الموقع",
    contact: "التواصل",
    details: "التفاصيل",
    amenities: "المرافق",
    policies: "السياسات",
    pricing: "التسعير",
    status: "الحالة",
    active: "نشط",
    inactive: "غير نشط",
    description: "الوصف",
    address: "العنوان",
    city: "المدينة",
    country: "الدولة",
    phone: "الهاتف",
    website: "الموقع الإلكتروني",
    type: "النوع",
    stars: "النجوم",
    saving: "جاري الحفظ...",
    // User Form Modal
    createNewUser: "إنشاء مستخدم جديد",
    editUser: "تعديل المستخدم",
    createUser: "إنشاء مستخدم",
    updateUser: "تحديث المستخدم",
    basicInfoTab: "المعلومات الأساسية",
    permissionsTab: "الصلاحيات",
    fullName: "الاسم الكامل",
    emailAddress: "البريد الإلكتروني",
    leaveEmptyPassword: "(اتركه فارغاً للاحتفاظ بالحالي)",
    linkedAdmin: "المدير المرتبط (الشركة)",
    adminRequired: "المدير مطلوب لهذا النوع من الحسابات",
    selectAdmin: "-- اختر مديراً --",
    logoUpload: "صورة الشعار",
    logoPreview: "معاينة الشعار",
    roleDescription: "وصف الدور",
    useCustomPerms: "استخدام صلاحيات مخصصة (تجاوز الافتراضيات)",
    selectAll: "تحديد الكل",
    clearAll: "مسح الكل",
    applyRolePreset: "تطبيق الصلاحيات الافتراضية",
    permissionsSelected: "صلاحية محددة",
    permSummary: "ملخص الصلاحيات",
    noPermsSelected: "لا توجد صلاحيات محددة",
    // Role names & descriptions
    role_super_admin: "مسؤول رئيسي",
    role_admin: "مدير (شركة)",
    role_hotel: "حساب فندق",
    role_restaurant: "حساب مطعم",
    role_activity: "حساب نشاط",
    role_hotel_manager: "مدير فندق",
    role_restaurant_manager: "مدير مطعم",
    role_activity_manager: "مدير نشاط",
    roleDesc_super_admin:
      "وصول كامل لجميع ميزات النظام. يمكنه إدارة جميع المستخدمين والفنادق والمطاعم والأنشطة وإعدادات النظام.",
    roleDesc_admin:
      "مسؤول الشركة. يمكنه إدارة الفنادق والمطاعم والأنشطة التابعة لشركته.",
    roleDesc_hotel:
      "مدير الفندق. يمكنه إدارة الغرف والحجوزات وعرض التقارير الخاصة بفندقه.",
    roleDesc_restaurant:
      "مدير المطعم. يمكنه إدارة الطاولات والحجوزات وعرض تقارير المطعم.",
    roleDesc_activity: "مدير النشاط. يمكنه إدارة الأنشطة والحجوزات الخاصة بها.",
    // Permission modules
    module_users: "إدارة المستخدمين",
    module_hotels: "الفنادق",
    module_restaurants: "المطاعم",
    module_activities: "الأنشطة",
    module_bookings: "الحجوزات",
    module_rooms: "الغرف / الطاولات",
    module_finance: "المالية",
    module_reports: "التقارير",
    module_settings: "الإعدادات",
    // Permission actions
    action_view_users: "عرض المستخدمين",
    action_add_users: "إضافة مستخدمين",
    action_edit_users: "تعديل المستخدمين",
    action_delete_users: "حذف المستخدمين",
    action_view_hotels: "عرض الفنادق",
    action_add_hotels: "إضافة فنادق",
    action_edit_hotels: "تعديل الفنادق",
    action_delete_hotels: "حذف الفنادق",
    action_view_restaurants: "عرض المطاعم",
    action_add_restaurants: "إضافة مطاعم",
    action_edit_restaurants: "تعديل المطاعم",
    action_delete_restaurants: "حذف المطاعم",
    action_view_activities: "عرض الأنشطة",
    action_add_activities: "إضافة أنشطة",
    action_edit_activities: "تعديل الأنشطة",
    action_delete_activities: "حذف الأنشطة",
    action_view_bookings: "عرض الحجوزات",
    action_add_bookings: "إضافة حجوزات",
    action_edit_bookings: "تعديل الحجوزات",
    action_delete_bookings: "حذف الحجوزات",
    action_view_rooms: "عرض الغرف",
    action_add_rooms: "إضافة غرف",
    action_edit_rooms: "تعديل الغرف",
    action_delete_rooms: "حذف الغرف",
    action_view_finance: "عرض المالية",
    action_add_finance: "إضافة معاملات",
    action_edit_finance: "تعديل المعاملات",
    action_delete_finance: "حذف المعاملات",
    action_view_reports: "عرض التقارير",
    action_view_settings: "عرض الإعدادات",
    action_edit_settings: "تعديل الإعدادات",
    dangerLabel: "خطر",
    allLabel: "الكل",
    // Admins page
    adminsManagement: "إدارة المدراء",
    adminsSubtitle: "مسؤولو الشركات — يديرون الفنادق والمطاعم والأنشطة",
    addAdmin: "+ إضافة مدير",
    totalAdmins: "إجمالي المدراء",
    withPermissions: "لديهم صلاحيات",
    managedAccounts: "الحسابات المُدارة",
    editAdmin: "تعديل المدير",
    areYouSureDeleteAdmin: "هل أنت متأكد من حذف هذا المدير؟",
    loadingAdmins: "جاري تحميل المدراء...",
    errorLoadingAdmins: "خطأ في تحميل المدراء",
    permissionsLabel: "الصلاحيات",
    moreLabel: "المزيد",
    // Hotels page
    hotelAccounts: "حسابات الفنادق",
    hotelAccountsSubtitle:
      "إدارة حسابات مستخدمي الفنادق — يجب ربط كل حساب بمدير",
    addHotelAccount: " إضافة حساب فندق",
    linkedToAdmin: "مرتبط بمدير",
    noAdminLinked: "بلا مدير",
    noAdminWarning: "بلا مدير",
    loadingHotelAccounts: "جاري تحميل حسابات الفنادق...",
    errorLoadingData: "خطأ في تحميل البيانات",
    hotelAccountsTable: "جميع حسابات الفنادق (عرض الجدول)",
    areYouSureDeleteHotelAccount: "هل أنت متأكد من حذف حساب الفندق هذا؟",
    noHotelAccountsYet:
      'لا توجد حسابات فنادق بعد. انقر على "+ إضافة حساب فندق" لإنشاء واحد.',
    // SuperAdmin dashboard
    superAdminOverview: "نظرة عامة على المدير الرئيسي",
    managePlatformResources: "إدارة جميع موارد المنصة من هنا.",
    superAdminUsers: "مستخدمو المدير الرئيسي",
    bookings: "الحجوزات",
    // Table column labels
    guest: "الضيف",
    checkIn: "تسجيل الوصول",
    checkOut: "تسجيل المغادرة",
    capacity: "السعة",
    roomTableNum: "رقم الغرفة/الطاولة",
    date: "التاريخ",
    revenue: "الإيرادات",
    expenses: "المصروفات",
    reportTitle: "التقرير",
    generatedAt: "تاريخ الإنشاء",
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem("lang") || "en");
  const [theme, setTheme] = useState(
    () => localStorage.getItem("theme") || "light",
  );

  useEffect(() => {
    localStorage.setItem("lang", lang);
    document.documentElement.dir = translations[lang].dir;
    document.documentElement.lang = lang;
  }, [lang]);

  useEffect(() => {
    localStorage.setItem("theme", theme);
    if (theme === "dark") {
      document.documentElement.classList.add("dark");
    } else {
      document.documentElement.classList.remove("dark");
    }
  }, [theme]);

  const toggleLang = () => setLang((l) => (l === "en" ? "ar" : "en"));
  const toggleTheme = () => setTheme((t) => (t === "light" ? "dark" : "light"));

  const t = (key) => translations[lang][key] || key;

  return (
    <LanguageContext.Provider
      value={{
        lang,
        toggleLang,
        t,
        dir: translations[lang].dir,
        theme,
        toggleTheme,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
